# Generated file used for preloading a child image
set(CMAKE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE INTERNAL "NCS child image controlled")
set(BOARD_DIR "C:/Nordic/SDKs/ncs/v2.6.0/zephyr/boards/arm/nrf52840dk_nrf52840" CACHE INTERNAL "NCS child image controlled")
set(ZEPHYR_TOOLCHAIN_VARIANT "zephyr" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "NONE" CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON "C:/Nordic/SDKs/ncs/toolchains/cf2149caf2/opt/bin/python.exe" CACHE INTERNAL "NCS child image controlled")
set(BOARD "nrf52840dk_nrf52840" CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE "C:/Nordic/SDKs/ncs/v2.6.0/nrf/modules/mcuboot/usb.overlay;C:/Nordic/SDKs/ncs/my_projects/samples_for_NCS/DFU/smp_ble_feat_spi/child_image/mcuboot.overlay" CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG "C:/Nordic/SDKs/ncs/v2.6.0/nrf/subsys/partition_manager/ext_flash_mcuboot_secondary.conf;C:/Nordic/SDKs/ncs/v2.6.0/nrf/subsys/partition_manager/partition_manager_enabled.conf;C:/Nordic/SDKs/ncs/my_projects/samples_for_NCS/DFU/smp_ble_feat_spi/child_image/mcuboot.conf" CACHE INTERNAL "NCS child image controlled")
